### ISSUE TITLE
Err in stm32duino/Arduino_Core_STM32

### ISSUE THREAD

**Issue by bignest** [k164v/DAC8562#1]
Hello！
I already run this lib on UNO,working good！
But when I try it in STM32 C8T6，there is Err： 
Arduino\libraries\DAC8562-master/DAC8562.h:69:39: error: 'u16' has not been declared
   69 |     void outPutValue(uint8_t cmd_byte,u16 input);
      |                                       ^~~
Arduino\libraries\DAC8562-master/DAC8562.h:74:5: error: 'u16' does not name a type; did you mean 'D16'?
   74 |     u16 DAC8562::Voltage_Convert(float voltage);
  the "u16"means “unsignedshort”，I change the"u16" to"unsigned short int",but still Err

Please help

**Comment by k164v** [comment]
@bignest I am sorry I never had any experiences with STM32 nor personally own one. I feel bad to say so but , your are on your own.

**Comment by k164v** [comment]
> Hello！
> I already run this lib on UNO,working good！
> But when I try it in STM32 C8T6，there is Err：
> Arduino\libraries\DAC8562-master/DAC8562.h:69:39: error: 'u16' has not been declared
> 69 | void outPutValue(uint8_t cmd_byte,u16 input);
> | ^~~
> Arduino\libraries\DAC8562-master/DAC8562.h:74:5: error: 'u16' does not name a type; did you mean 'D16'?
> 74 | u16 DAC8562::Voltage_Convert(float voltage);
> the "u16"means “unsignedshort”，I change the"u16" to"unsigned short int",but still Err
> 
> Please help

Also, feel free to contribute to it if you ever solved the problem!
